name: pay_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  persistent_bottom_nav_bar: ^5.0.0

  cupertino_icons: ^1.0.8
  icons_plus: ^4.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  google_sign_in: ^5.4.0 
  mobile_scanner: ^6.0.1
  http: ^0.13.3
  flutter_stripe: ^11.2.0

# card_flutter: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets (images, fonts, etc.)
  assets:
    - assets/images/start.png

  # Add custom fonts section here:
  fonts:
  - family: LeagueSpartan
    fonts:
      - asset: assets/fonts/LeagueSpartan-ExtraLight.ttf
      - asset: assets/fonts/LeagueSpartan-Light.ttf
      - asset: assets/fonts/LeagueSpartan-Thin.ttf
      - asset: assets/fonts/LeagueSpartan-Medium.ttf
      - asset: assets/fonts/LeagueSpartan-Regular.ttf
      - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
      - asset: assets/fonts/LeagueSpartan-Bold.ttf
      - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
      - asset: assets/fonts/LeagueSpartan-Black.ttf

