name: test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0


  cupertino_icons: ^1.0.8
  icons_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets (images, fonts, etc.)
  assets:
    - assets/images/start.png

  # Add custom fonts section here:
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
